### ISSUE TITLE
some questions about the paper and code

### ISSUE THREAD

**Issue by GuChenghs** [kjunelee/MetaOptNet#12]
Thank you for sharing your paper and code.
After I finished reading, I have some questions. Implied in the article,‘For SVM and ridge regression, we observe that keeping meta-training shot higher than meta-testing shot leads to better test accuracies as shown in Figure 2.’ 
![image](https://user-images.githubusercontent.com/48040018/59908930-1ce3ff80-9441-11e9-83b8-4325f8ee015f.png)
Does this mean that the number of training samples during the meta-train is different from the number of training samples during the meta-test? However，I think in order to better measure the ability of generalization , shouldn't these two parameters be consistent? In addition, when I studied the code, I was confused about ‘train-shot’, ‘val-shot’, ‘train-query’, ‘val-query’, I hope you can explain these.
Look forward to your reply.

**Comment by kjunelee** [comment]
Thanks for your interest in our paper.

Q1: Does this mean that the number of training samples during the meta-train is different from the number of training samples during the meta-test?
A1: Yes. The result in Figure 2 is an empirical result and we are not very sure why this phenomenon is happening.

Q2: I was confused about ‘train-shot’, ‘val-shot’, ‘train-query’, ‘val-query’, I hope you can explain these.
A2: ‘train-shot’ means number of training examples for each category per episode during meta-training. 
‘val-shot’ means number of training examples for each category per episode during meta-validation.
‘train-query’ means number of test (query) examples per episode during meta-training.
‘val-query’ means number of test (query) examples per episode during meta-validation.

**Comment by GuChenghs** [comment]
Thank you for your reply.
When it comes to 'K-way,N-shot',‘ Here K denotes the number of classes, and N denotes the number of training examples per class.’，Implied in the article.Does these mean K-way and N-shot during meta-testing?

**Comment by kjunelee** [comment]
Yes.
