### ISSUE TITLE
about input data (pickle files) 

### ISSUE THREAD

**Issue by xmengli999** [kjunelee/MetaOptNet#13]
Thanks for sharing the code. 

I noticed that you use "miniImageNet_category_split_train_phase_val.pickle", where this file consists of 300 images of train class.  How did you choose the images from the train class?
And, what is the difference between "miniImageNet_category_split_train_phase_val.pickle" and 'miniImageNet_category_split_train_phase_test.pickle'?

**Comment by xmengli999** [comment]
In the miniImagenet dataset, training data have 64 class and each class have 600 samples. I am wondering how did you select 300 samples from 600 samples in each class?

**Comment by kjunelee** [comment]
In practice, images from miniImageNet_category_split_train_phase_val.pickle is never used for our case.
The dataset is derived from the CVPR 2018 paper from Gidaris et al.: https://github.com/gidariss/FewShotWithoutForgetting
and their paper has a problem setting of testing on base classes (and this needs to read fromminiImageNet_category_split_train_phase_val.pickle).
In our paper, we only test on novel classes as in many other few-shot learning paper.

**Comment by xmengli999** [comment]
Thank you !
