### ISSUE TITLE
Can this code be used for MetaOptNet-SVM-trainval?

### ISSUE THREAD

**Issue by FrigEgg** [kjunelee/MetaOptNet#18]
I see the code there are not commands that can train  MetaOptNet-SVM-trainval, can it?

**Comment by kjunelee** [comment]
I created a separate pickle file for trainval dataset which is currently not uploaded in our GitHub repository.

**Comment by FrigEgg** [comment]
I see. Thank you!

**Comment by xcmax** [comment]
Could you plz upload trainval dataset for both Miniimagenet and FC100 and the other one?
If I fix this by myself, should I just concate these two sets?

**Comment by kjunelee** [comment]
miniImageNet: https://drive.google.com/file/d/1QKngW-HuqZLUpb6HnwgT_jNhRFdiEZR9/view?usp=sharing
FC100: https://drive.google.com/file/d/1gXW7e_xZXkdaju7W6DV4M7VrIsHUrHzJ/view?usp=sharing
