### ISSUE TITLE
Is Label smoothing for SVM only used in miniImageNet?

### ISSUE THREAD

**Issue by FrigEgg** [kjunelee/MetaOptNet#19]
I am sorry to ask so many questions. The papers I will follow will definitely include and reference MetaOptNet.

**Comment by FrigEgg** [comment]
I mean. Is there label smoothing is used in CIFAR-FS, FC100 and tieredImageNet?

**Comment by kjunelee** [comment]
Label smoothing was effective only on miniImageNet experiments with ResNet.

**Comment by FrigEgg** [comment]
OK, thank you very much!
