### ISSUE TITLE
Reproducability about ProtoNet on mini-ImageNet

### ISSUE THREAD

**Issue by hankook** [kjunelee/MetaOptNet#25]
I am currently trying to reproduce results on mini-ImageNet using ProtoNet based on your code.

However, when I run the below script for training ProtoNet, it achieves 57% on the test set, but the reported accuracy is 59%.
```
python train.py --gpu 0,1,2,3 --save-path "./experiments/miniImageNet_MetaOptNet_ProtoNet" --train-shot 1 --val-shot 1 \
--head ProtoNet --network ResNet --dataset miniImageNet --eps 0.1
```
I wonder how to achieve the reported accuracy.

If you don't mind, can you tell me how you train ProtoNet on mini-ImageNet?

**Comment by kjunelee** [comment]
Sorry for the late reply. At the moment, I don't have a GPU server to run experiments on miniImageNet. Let me get back to this in few days.
