### ISSUE TITLE
qpth warning: Returning an inaccurate and potentially incorrect solutino.

### ISSUE THREAD

**Issue by LYF14020510036** [kjunelee/MetaOptNet#29]
qpth warning: Returning an inaccurate and potentially incorrect solutino.

Some residual is large.
Your problem may be infeasible or difficult.

You can try using the CVXPY solver to see if your problem is feasible
and you can use the verbose option to check the convergence status of
our solver while increasing the number of iterations.

Advanced users:
You can also try to enable iterative refinement in the solver:
https://github.com/locuslab/qpth/issues/6

Hi, could you tell me, is this normal? Why does this happen? Thank you.

**Comment by kjunelee** [comment]
I believe this happens when you run meta-test code where we early stop the convex optimizer. This is a normal behavior.

**Comment by LYF14020510036** [comment]
Thank you very much for your reply.
