### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by hytseng0509** [kjunelee/MetaOptNet#30]
Hi,

Thanks for sharing the source code! 
I'm wondering if you can provide the mode file you use to report the number in the paper. In particular, I would like to ask for the model file "MetaOptNet-SVM-trainval" evaluated on the 5-shot mini-ImageNet classification (which reports 80.00 ± 0.45%). Thanks!

**Comment by kjunelee** [comment]
Hi I was able to find a pertained model with 5-shot performance of 79.90 ± 0.44 % in my server. Here it is:
https://drive.google.com/file/d/1NQHE1fCflrEDrBxz_6QURJUZ2JPWZZtJ/view?usp=sharing
Hope this helps.

**Comment by hytseng0509** [comment]
Thanks!
