### ISSUE TITLE
def MetaOptNetHead_Ridge()

### ISSUE THREAD

**Issue by LYF14020510036** [kjunelee/MetaOptNet#31]
Your work is really excellent. Could you give me a simple analysis of the function metaoptnethead_ridge in classification_heads.py. Thank you.

**Comment by LYF14020510036** [comment]
Can I understand the function metaoptnethead_ridge as a combination of SVM and ridge expression

**Comment by kjunelee** [comment]
metaoptnethead_ridge computes the quadratic programming of Equation (11) in our paper. Since ridge regression has a closed-form solution, you can instead call R2D2Head function to obtain the same solution.

**Comment by LYF14020510036** [comment]
Thank you very much for your reply. Benefited a lot.
