### ISSUE TITLE
Formula (11)  in your paper.

### ISSUE THREAD

**Issue by LYF14020510036** [kjunelee/MetaOptNet#32]
![image](https://user-images.githubusercontent.com/30076500/69009593-a583af00-0991-11ea-88ac-834970bca159.png)

Is ridge expression not linear regression plus L2 loss? Is this formula also ridge regression?

**Comment by kjunelee** [comment]
This is a ridge regression in dual form. We can derive it from primal form by plugging in Eq (9).
