### ISSUE TITLE
RuntimeError with qpth

### ISSUE THREAD

**Issue by lhfowl** [kjunelee/MetaOptNet#35]
Hello, 

I've been trying to run some MetaOptNet experiments. I've created a conda environment with the packages you list as required. However, when I try to train MetaOptNet with SVM head, I'm getting the error: 

"RuntimeError: Incompatible matrix sizes for lu_solve: each A matrix is 25 by 25 but each b matrix is 8 by 25" 

I've tried using environments with different versions of python, but can't seem to get around this issue. I'm at a loss. Have you run into this issue before? Any advice would be greatly appreciated.

**Comment by kjunelee** [comment]
I guess the issue has to do with package versions. I am able to run under the following configuration:

Python 3.6.8
qpth 0.0.13
PyTorch 1.1.0a0+b75a525

Hope this helps.

**Comment by lhfowl** [comment]
Okay, thanks!
