### ISSUE TITLE
Why dual formulation in Bertinetto's regression solver?

### ISSUE THREAD

**Issue by arxrean** [kjunelee/MetaOptNet#36]
Hi, I'm new to this. I read both your paper and Bertinetto's. In their paper, the closed form solver is derived by classicial regression or Newton’s method. There is no dual form needed in theirs. But in your paper, their solution has a dual form. Does it contain some hidden processes? Thank you!

**Comment by kjunelee** [comment]
You can find the derivation of dual ridge regression e.g. in "Ridge Regression Learning Algorithm in Dual Variables" by Saunders et al. (1998).

Hope this helps.
