### ISSUE TITLE
Some questions about MetaOptNetHead_Ridge

### ISSUE THREAD

**Issue by WHQ1111** [kjunelee/MetaOptNet#39]
I have read you code , and I think there may be some wrong about the function 'MetaOptNetHead_Ridge' in classification_heads.py. I think it should be

                        e = -1.0 * support_labels_one_hot
not 
      
                       e = -2.0 * support_labels_one_hot

And the equation (11) should be minimize not maximize. Am I right?

**Comment by kjunelee** [comment]
This is a great question. I had the same confusion when I worked on this project. If you try the one with -2.0, you will empirically observe that it performs worse than the one with -1.0.

The implementation is correct, but there is a typo in the equation (11) of the paper. I apologize for the confusion. The correct equation should look like this:
![image](https://user-images.githubusercontent.com/25063425/74631036-c8e50400-5110-11ea-95a2-5bb89f0ec949.png)
Please refer to the derivation of dual ridge regression e.g. in "Ridge Regression Learning Algorithm in Dual Variables" by Saunders et al. (1998).

**Comment by WHQ1111** [comment]
Thank you very much. I get it.
