### ISSUE TITLE
About accuracy in CIFAR_FS 5-way 5-shot and how to implement MetaOptNet-SVM-trainval

### ISSUE THREAD

**Issue by WHQ1111** [kjunelee/MetaOptNet#40]
I like you work very much and it give us many inspirement.
But when I use it at CIFAR_FS 5-way 5-shot and I get 83.89 ± 0.51% accuracy. I think the reason maybe that I used MetaOptNet-SVM not MetaOptNet-SVM-trainval. So I want know how to implement MetaOptNet-SVM-trainval. Thank you very much.

**Comment by kjunelee** [comment]
trainval set was generated by opening train set pickle file and val set pickle file in Python and concatenating them together.
Please email me at kwl042@eng.ucsd.edu if you wish to get python file for merging splits.

**Comment by kjunelee** [comment]
This is the link to CIFAR_FS_train_val:
https://drive.google.com/open?id=1CI4kt7Plru6IX5Fp8dIocG1a5Yc5UcAk
