### ISSUE TITLE
Data type problem

### ISSUE THREAD

**Issue by GuChenghs** [kjunelee/MetaOptNet#7]
Thank you for your code.
I ran your program and encountered this problem, as shown in the figure. I can't solve it for now. I am using python3.6.

![捕获](https://user-images.githubusercontent.com/48040018/56797545-7ec02880-6847-11e9-8781-3967c5304542.PNG)

**Comment by kjunelee** [comment]
Updated the code. Now it should solve the problem.

**Comment by GuChenghs** [comment]
Thank you for your help, the program is ready to run.

**Comment by MAT0RIX** [comment]
Is this problem only appears when running on a single GPU?
I will try to run it again.
Thx
